# -*- coding: utf-8 -*-
"""Faculty_Promotion_Binary_Model_SMOTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jws0N3VxKHoe0dwqzrKXcEVRBhlvjLKo

# Faculty Promotion Binary Classification (SMOTE Balanced)
This version applies SMOTE to balance the training data.
"""

# Imports
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

from imblearn.over_sampling import SMOTE

# Load dataset
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Datasets/TQE.csv'
df = pd.read_csv(file_path)

print("Dataset Shape:", df.shape)
df.head()

# Load data (update path if needed)
df = df.copy()  # assumes df already exists if run after original loading cell

# The previous code failed because the column 'Promotion' was not found in the DataFrame.
# The available columns are: 'Teacher_ID', 'Course_ID', 'Semester', 'Teaching Effectiveness',
# 'Curriculum and Instructional Materials Development', 'Thesis, Dissertation and Mentorship Services',
# 'Research Outputs', 'Inventions', 'Creative Works', 'Service to the Institution',
# 'Service to the Community', 'Extension Involvement', 'Professional Development', 'Teaching_Quality'.
#
# Assuming 'Teaching_Quality' is intended to be used as the target variable,
# and for a "Binary Classification" as per the notebook title, we will
# binarize 'Teaching_Quality' where 'Excellent' indicates a positive class (e.g., promotion)
# and other values indicate a negative class (e.g., no promotion).

# Binarize 'Teaching_Quality' to create the target variable 'Promotion'
df['Promotion'] = df['Teaching_Quality'].apply(lambda x: 1 if x == 'Excellent' else 0)

# Now, we can define features (X) and target (y)
# Drop 'Teacher_ID', 'Course_ID', 'Semester', and original 'Teaching_Quality' as they are not numerical features
# and 'Teaching_Quality' has been used to create 'Promotion'.
X = df.drop(['Promotion', 'Teacher_ID', 'Course_ID', 'Semester', 'Teaching_Quality'], axis=1)
y = df['Promotion']

print("X shape:", X.shape)
print("y value counts:\n", y.value_counts())
print("\nFirst 5 rows of X:")
print(X.head())
print("\nFirst 5 values of y:")
print(y.head())

# Numerical preprocessing
numerical_cols = X.select_dtypes(include=np.number).columns

num_imputer = SimpleImputer(strategy='mean')
X_num = num_imputer.fit_transform(X[numerical_cols])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_num)

X_processed = pd.DataFrame(X_scaled, columns=numerical_cols, index=X.index)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE only on training data
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts().to_dict())
print("After SMOTE:", y_train_sm.value_counts().to_dict())

# Models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results).sort_values(by="F1-Score", ascending=False)
results_df

# Train best model and evaluate
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)

y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

print("Best Model:", best_model_name)
print("Confusion Matrix:\n", cm)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, auc

# 1. Confusion Matrix Visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title(f'Confusion Matrix for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# 2. ROC Curve Visualization
# Recalculate y_prob for the best model to ensure correctness
y_prob_best = best_model.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title(f'Receiver Operating Characteristic (ROC) Curve for {best_model_name}')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

feature_importance = pd.DataFrame({
    'Feature': X_processed.columns,
    'Importance': best_model.coef_[0]
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importance Table:")
print(feature_importance)



"""# Task
Create a heatmap visualization of the confusion matrix with explicit labels for True Positives, False Positives, True Negatives, and False Negatives, and plot the Receiver Operating Characteristic (ROC) curve with labels indicating different classification thresholds (cutoffs) along the curve.

## Generate Binary Confusion Matrix with TP/FP/TN/FN Labels

### Subtask:
Create a heatmap visualization of the confusion matrix with explicit labels for True Positives, False Positives, True Negatives, and False Negatives.

**Reasoning**:
The user wants to visualize the confusion matrix with explicit TP, FP, TN, FN labels. I will use the previously calculated confusion matrix (`cm`) and `best_model_name` to create a heatmap with custom annotations as per the instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""**Reasoning**:
The previous code failed because the variable `cm` was not defined in the current execution context. To fix this, I will re-include the necessary code from the previous successful cell that calculates the confusion matrix (`cm`) and determines the `best_model_name`, ensuring these variables are available before being used for plotting the confusion matrix with custom labels.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix

# Re-calculating cm and best_model_name to ensure they are defined
# (Assuming results_df, models, X_train_sm, y_train_sm, X_test, y_test are available from previous successful cells)
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""**Reasoning**:
The previous code failed because `results_df`, `models`, `X_train_sm`, `y_train_sm`, `X_test`, and `y_test` were not defined in the current execution context. I need to re-include the code that initializes these variables before they are used to calculate the confusion matrix and plot it.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE

# Assuming df, X_processed, and y are available from previous successful cells.
# Re-define necessary variables from prior cells to ensure context

# Train-test split (from cell c0ad9f47)
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE only on training data (from cell c0ad9f47)
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Models (from cell 89f2842b)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results).sort_values(by="F1-Score", ascending=False)

# Get best model name and fit (from cell 812213a3)
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""**Reasoning**:
The previous code failed because `X_processed` was not defined. I need to include the steps that define `X` and `y` from `6cd24952` and then the numerical preprocessing steps to create `X_processed` from `856f7763` before proceeding with train-test split, SMOTE, model training, and plotting.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# --- Re-execute necessary prior steps to define variables ---

# Assuming df exists from cell mp-Agx7EKW_r
# If df does not exist in the environment, the following lines would need to be uncommented and potentially adapted.
# from google.colab import drive
# drive.mount('/content/drive')
# file_path = '/content/drive/MyDrive/Datasets/TQE.csv'
# df = pd.read_csv(file_path)

# Binarize 'Teaching_Quality' to create the target variable 'Promotion' (from cell 6cd24952)
df['Promotion'] = df['Teaching_Quality'].apply(lambda x: 1 if x == 'Excellent' else 0)

# Define features (X) and target (y) (from cell 6cd24952)
X = df.drop(['Promotion', 'Teacher_ID', 'Course_ID', 'Semester', 'Teaching_Quality'], axis=1)
y = df['Promotion']

# Numerical preprocessing (from cell 856f7763)
numerical_cols = X.select_dtypes(include=np.number).columns

num_imputer = SimpleImputer(strategy='mean')
X_num = num_imputer.fit_transform(X[numerical_cols])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_num)

X_processed = pd.DataFrame(X_scaled, columns=numerical_cols, index=X.index)

# --- End of re-executed prior steps ---

# Train-test split (from cell c0ad9f47)
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE only on training data (from cell c0ad9f47)
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Models (from cell 89f2842b)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results).sort_values(by="F1-Score", ascending=False)

# Get best model name and fit (from cell 812213a3)
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""**Reasoning**:
The previous code failed because the `df` DataFrame was not defined. I need to include the original data loading steps from the notebook's initial cells to ensure `df` is available, along with all subsequent processing steps (`X`, `y`, `X_processed`, `train_test_split`, `SMOTE`, `models` definition, `results_df`, `best_model`, `cm`) before attempting to plot the confusion matrix.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# --- Re-execute necessary prior steps to define variables ---

# Load dataset (from cell mp-Agx7EKW_r)
# from google.colab import drive
# drive.mount('/content/drive') # Assuming drive is already mounted based on previous output
file_path = '/content/drive/MyDrive/Datasets/TQE.csv'
df = pd.read_csv(file_path)

# Binarize 'Teaching_Quality' to create the target variable 'Promotion' (from cell 6cd24952)
df['Promotion'] = df['Teaching_Quality'].apply(lambda x: 1 if x == 'Excellent' else 0)

# Define features (X) and target (y) (from cell 6cd24952)
X = df.drop(['Promotion', 'Teacher_ID', 'Course_ID', 'Semester', 'Teaching_Quality'], axis=1)
y = df['Promotion']

# Numerical preprocessing (from cell 856f7763)
numerical_cols = X.select_dtypes(include=np.number).columns

num_imputer = SimpleImputer(strategy='mean')
X_num = num_imputer.fit_transform(X[numerical_cols])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_num)

X_processed = pd.DataFrame(X_scaled, columns=numerical_cols, index=X.index)

# --- End of re-executed prior steps ---

# Train-test split (from cell c0ad9f47)
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE only on training data (from cell c0ad9f47)
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Models (from cell 89f2842b)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results).sort_values(by="F1-Score", ascending=False)

# Get best model name and fit (from cell 812213a3)
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""**Reasoning**:
The previous code failed because the CSV file was not found, indicating a potential issue with the Google Drive mount or file path accessibility in the current execution context. I will re-add `from google.colab import drive` and `drive.mount('/content/drive')` to ensure the drive is mounted and the file is accessible before reloading the data and re-executing all subsequent processing steps.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# --- Re-execute necessary prior steps to define variables ---

# Load dataset (from cell mp-Agx7EKW_r)
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/Datasets/TQE.csv'
df = pd.read_csv(file_path)

# Binarize 'Teaching_Quality' to create the target variable 'Promotion' (from cell 6cd24952)
df['Promotion'] = df['Teaching_Quality'].apply(lambda x: 1 if x == 'Excellent' else 0)

# Define features (X) and target (y) (from cell 6cd24952)
X = df.drop(['Promotion', 'Teacher_ID', 'Course_ID', 'Semester', 'Teaching_Quality'], axis=1)
y = df['Promotion']

# Numerical preprocessing (from cell 856f7763)
numerical_cols = X.select_dtypes(include=np.number).columns

num_imputer = SimpleImputer(strategy='mean')
X_num = num_imputer.fit_transform(X[numerical_cols])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_num)

X_processed = pd.DataFrame(X_scaled, columns=numerical_cols, index=X.index)

# --- End of re-executed prior steps ---

# Train-test split (from cell c0ad9f47)
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE only on training data (from cell c0ad9f47)
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Models (from cell 89f2842b)
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results).sort_values(by="F1-Score", ascending=False)

# Get best model name and fit (from cell 812213a3)
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_model.fit(X_train_sm, y_train_sm)
y_pred_best = best_model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_best)

# Define the labels for the confusion matrix cells
labels = np.array([['True Negatives', 'False Positives'],
                   ['False Negatives', 'True Positives']])

# Create a new figure and axes for the confusion matrix visualization
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', cbar=False,
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.title(f'Confusion Matrix with TP/FP/TN/FN Labels for {best_model_name}')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""## Generate ROC Curve with Cutoff Labels

### Subtask:
Plot the Receiver Operating Characteristic (ROC) curve and add markers or labels to indicate different classification thresholds (cutoffs) along the curve.

## Summary:

### Data Analysis Key Findings
*   A heatmap visualization of the confusion matrix was successfully generated for the best-performing model (based on F1-Score).
*   The heatmap explicitly labeled the four cells as 'True Negatives', 'False Positives', 'False Negatives', and 'True Positives'.
*   The visualization included 'Predicted Label' on the x-axis and 'True Label' on the y-axis, along with a title indicating the model used.

### Insights or Next Steps
*   Ensure all dependencies, including data loading, preprocessing, model training, and selection, are executed within the current session to avoid `NameError` or `FileNotFoundError` when regenerating visualizations or results.
*   The next step is to plot the Receiver Operating Characteristic (ROC) curve with labels indicating different classification thresholds (cutoffs), as originally specified in the task description.

# Task
Plot the Receiver Operating Characteristic (ROC) curve and add labels to indicate different classification thresholds (cutoffs) along the curve.

## Generate ROC Curve with Cutoff Labels

### Subtask:
Plot the Receiver Operating Characteristic (ROC) curve and add markers or labels to indicate different classification thresholds (cutoffs) along the curve.

**Reasoning**:
The previous code block successfully set up all data, models, and found the best model. Now, I need to generate the ROC curve for the best model, calculate the thresholds, and then plot the ROC curve with annotations for these thresholds as requested in the subtask.

**Reasoning**:
The previous code failed because `step_size` became zero when the number of `thresholds` was less than 10, causing a `ValueError` in the `range()` function. To fix this, I will ensure `step_size` is at least 1 by using `max(1, len(thresholds) // 10)`.
"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
import numpy as np

# Get probabilities for the best model
y_prob_best = best_model.predict_proba(X_test)[:, 1]

# Calculate FPR, TPR, and thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
roc_auc = auc(fpr, tpr)

# Plot the ROC curve
plt.figure(figsize=(10, 8))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')

# Add threshold labels to the ROC curve for a subset of thresholds
# We'll select a few representative thresholds to avoid cluttering the plot
# For example, every 50th threshold, or specific thresholds like 0.2, 0.4, 0.6, 0.8

# Let's try to annotate around 10-15 points on the curve
# Calculate step size to select a reasonable number of thresholds
# Ensure step_size is at least 1 to avoid ValueError for range()
step_size = max(1, len(thresholds) // 10)

for i in range(0, len(thresholds), step_size):
    # Ensure we don't go out of bounds for the last point
    if i >= len(thresholds):
        break
    threshold = thresholds[i]
    # Avoid annotating thresholds too close to 0 or 1 if they are not impactful
    if threshold > 0.01 and threshold < 0.99: # Filter out extreme thresholds
        plt.plot(fpr[i], tpr[i], 'o', color='green', markersize=6)
        plt.annotate(f'{threshold:.2f}', (fpr[i], tpr[i]), textcoords="offset points", xytext=(5, -10), ha='center', fontsize=9, color='green')

# Add labels and title
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title(f'Receiver Operating Characteristic (ROC) Curve for {best_model_name} with Thresholds')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The Receiver Operating Characteristic (ROC) curve for the best model was successfully generated and plotted, illustrating the trade-off between the True Positive Rate (TPR) and the False Positive Rate (FPR) at various classification thresholds.
*   The Area Under the Curve (AUC) for the best model was calculated and displayed in the plot legend.
*   Key classification thresholds were annotated along the ROC curve, providing specific performance points (TPR and FPR) corresponding to different decision boundaries.
*   An initial error in the code due to a `ValueError` in the `range()` function (caused by `step_size` becoming 0) was identified and resolved by ensuring `step_size` is always at least 1 (`max(1, len(thresholds) // 10)`).

### Insights or Next Steps

*   The annotated ROC curve provides a valuable visual tool for understanding how the model's performance (TPR vs. FPR) changes with different classification cutoffs, which is crucial for selecting an appropriate decision threshold based on specific problem requirements.
*   Further analysis could involve exploring the impact of selecting different annotated thresholds on business metrics or misclassification costs to optimize model deployment.

"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(10, 8))

# Assuming 'models', 'X_test', and 'y_test' are available from previous cells
for name, model in models.items():
    # Predict probabilities for the positive class
    y_prob = model.predict_proba(X_test)[:, 1]

    # Calculate FPR, TPR, and thresholds
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    # Plot the ROC curve for the current model without rounding AUC
    plt.plot(fpr, tpr, lw=2, label=f'{name} (AUC = {roc_auc})')

# Plot the random guess line
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess (AUC = 0.5)')

# Add labels and title
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve Comparison (Unrounded AUC)')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
import numpy as np

# Get probabilities for the best model
y_prob_best = best_model.predict_proba(X_test)[:, 1]

# Calculate FPR, TPR, and thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
roc_auc = auc(fpr, tpr)

# Plot the ROC curve
plt.figure(figsize=(10, 8))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc})') # Removed .2f for unrounded AUC
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')

# Add threshold labels to the ROC curve for a subset of thresholds
# Ensure step_size is at least 1 to avoid ValueError for range()
step_size = max(1, len(thresholds) // 10)

for i in range(0, len(thresholds), step_size):
    if i >= len(thresholds):
        break
    threshold = thresholds[i]
    if threshold > 0.01 and threshold < 0.99:
        plt.plot(fpr[i], tpr[i], 'o', color='green', markersize=6)
        plt.annotate(f'{threshold:.2f}', (fpr[i], tpr[i]), textcoords="offset points", xytext=(5, -10), ha='center', fontsize=9, color='green')

# Add labels and title
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title(f'Receiver Operating Characteristic (ROC) Curve for {best_model_name} with Unrounded AUC and Thresholds')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()