import type { UploadPanelDefinition, UploadPanelKey } from './types';

export const uploadPanels: UploadPanelDefinition[] = [
  {
    key: 'kra1_teaching_effectiveness',
    kraTitle: 'KRA 1: Instruction',
    title: 'Teaching Effectiveness',
    description: 'Upload certified SET ratings and Supervisor Evaluation ratings with NBC 461 transmutation per term. For 2nd Semester AY 2025-2026, upload the FEDAF. Add approved study, maternity, or sabbatical leave proof when claiming special status.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_curriculum_instructional_materials',
    kraTitle: 'KRA 1: Instruction',
    title: 'Instructional Materials Development',
    description: 'Upload the applicable textbook, module, instructional manual, multimedia teaching material, or academic program documents with evaluation/approval proof, syllabus or course guide listing, library certification when applicable, and co-author contribution form when applicable.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_thesis_dissertation_mentorship',
    kraTitle: 'KRA 1: Instruction',
    title: 'Research Advising and Mentorship Services',
    description: 'For adviser or panel service, upload the approval sheet showing title, student, adviser/panel names, date of approval, and RRPA/COPC. For mentor or coach service, upload designation, student award proof, competition mechanics, and award-giving organization profile.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 10,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_research_outputs',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Research Outputs Published',
    description: 'Upload the applicable published book, edited book chapter, journal article, monograph, translated research, or cited publication with publication pages or article copy, peer-review/indexing proof, research director certification when required, and contribution form when co-authored.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_inventions',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Inventions',
    description: 'Upload the applicable invention photo, Special Order, IPOPHL patent/utility model/industrial design documents, commercialization proof, software copyright and utilization proof, or plant/animal/microbial registration and propagation or validation proof. Add contribution forms when applicable.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_creative_works',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Creative Works',
    description: 'Upload the applicable creative work evidence: score/script/film/publication/design portfolio or artwork photo, invitation or acceptance proof, program/catalog/flyer, performance/exhibition/screening documentation, certification from organizer/curator/director/publisher, and contribution form when applicable.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_institution',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to the Institution',
    description: 'For linkages or partnerships, upload SUC approval, notarized MOA/MOU or project proposal, implementation or terminal report, and certification of faculty initiative. For income generation, upload certified financial reports or fund-transfer proof plus Finance certification of your role.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_community',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to the Community',
    description: 'Upload the applicable appointment, invitation, contract, authorization, activity proof, certificate/report, program, organization profile, media proof, or extension Special Order, board-approved proposal, role evidence, and terminal/status report for community or professional service.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 50,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_extension_involvement',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Relevance and Quality of Extension Services',
    description: 'Upload the certified client satisfaction rating summary for outreach/extension projects, or the Extension Project CSS Report under CMO No. 18, s. 2025 for applicable 2025-2026 periods.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_administrative_designation',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Administrative Designation',
    description: 'Upload the appointment or designation with effectivity period and an accomplishment report submitted to the authorized immediate supervisor, or annual faculty association report for Faculty Trustee/Regent claims.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ADMIN_DESIGNATION_ONLY',
    audienceLabel: 'Bonus - only for faculty holding an administrative designation',
  },
  {
    key: 'kra4_professional_organizations',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Involvement in Professional Organizations',
    description: 'Upload valid membership certificate or ID, organization registration/profile and convention history where required, website link for international organizations, plus evidence of active role and certification from the organization head.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_continuing_development',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Continuing Development',
    description: 'Upload CAV transcript, diploma/equivalency/scholarship documents for qualifications; program, certificate, and approval to attend for seminars or conferences; and acceptance/invitation, program, presenter certificate, research director certification, and approval to present for papers.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_awards_recognition',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Awards and Recognition',
    description: 'Upload award description, certificate or photo of plaque/trophy/medal, award criteria and mechanics, selection process, and award-giving organization profile. For institutional awards, include approved PRAISE guidelines evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_academic_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Academic Experience',
    description: 'For newly appointed faculty only, upload service record, certificate of employment, notice of appointment/designation, or similar employment proof, plus a brief job description for full-time academic service in higher education.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
  {
    key: 'kra4_industry_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Industry Experience',
    description: 'For newly appointed faculty only, upload service record, certificate of employment, notice of appointment/designation, or similar employment proof, plus a brief job description for relevant non-academic industry experience.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
];

export const uploadPanelLabelMap: Record<UploadPanelKey, string> = uploadPanels.reduce(
  (labels, panel) => {
    labels[panel.key] = panel.title;
    return labels;
  },
  {} as Record<UploadPanelKey, string>,
);

export const uploadPanelKeywordMap: Record<UploadPanelKey, string[]> = {
  kra1_teaching_effectiveness: ['teaching effectiveness', 'student evaluation', 'supervisor evaluation', 'set', 'sef', 'fedaf', 'nbc 461', 'transmutation', 'study leave', 'maternity leave', 'sabbatical leave'],
  kra1_curriculum_instructional_materials: ['curriculum', 'instructional material', 'module', 'instructional manual', 'textbook', 'multimedia teaching material', 'academic program', 'evaluation report', 'approval for use', 'syllabus', 'course guide', 'library holdings', 'certificate of contribution'],
  kra1_thesis_dissertation_mentorship: ['thesis', 'dissertation', 'mentorship', 'mentor', 'coach', 'capstone', 'special project', 'approval sheet', 'rrpa', 'copc', 'award', 'competition mechanics'],
  kra2_research_outputs: ['research output', 'journal article', 'book chapter', 'academic book', 'monograph', 'citation', 'publication', 'peer review', 'scopus', 'web of science', 'asean citation index', 'research director', 'translated research', 'policy', 'product'],
  kra2_inventions: ['invention', 'patent', 'utility model', 'industrial design', 'software', 'commercialized', 'plant variety', 'animal breed', 'microbial strain', 'ipophil', 'ipophl', 'special order', 'formality examination', 'substantive examination', 'copyright certificate', 'licensing agreement'],
  kra2_creative_works: ['creative work', 'performing art', 'musical score', 'choreography', 'theatre', 'exhibition', 'design portfolio', 'film festival', 'literary', 'poetry', 'novel', 'short story', 'film', 'catalog', 'program', 'curator', 'publisher'],
  kra3_service_to_institution: ['institution', 'partnership', 'linkage', 'networking', 'income generation', 'suc approval', 'moa', 'mou', 'implementation report', 'terminal report', 'financial report', 'sub-aro', 'finance certification'],
  kra3_service_to_community: ['community', 'consultant', 'resource person', 'outreach', 'extension project', 'media', 'accreditation', 'quality assurance', 'judge', 'examiner', 'appointment', 'authorization', 'invitation', 'program', 'certificate of appreciation', 'special order'],
  kra3_extension_involvement: ['client satisfaction', 'quality of extension', 'extension service', 'outreach evaluation', 'css report', 'extension project css report', 'extension head', 'extension director'],
  kra3_administrative_designation: ['administrative designation', 'appointment', 'effectivity period', 'accomplishment report', 'department head', 'dean', 'committee chair', 'faculty trustee', 'faculty regent'],
  kra4_professional_organizations: ['professional organization', 'scientific society', 'membership', 'certificate of membership', 'membership id', 'sec registration', 'organizational profile', 'active participation', 'certification from the head'],
  kra4_continuing_development: ['continuing development', 'conference', 'seminar', 'workshop', 'industry immersion', 'degree', 'diploma', 'transcript of records', 'cav', 'certificate of participation', 'paper presenter', 'acceptance letter', 'approval to attend'],
  kra4_awards_recognition: ['award', 'recognition', 'distinction', 'plaque', 'trophy', 'medal', 'criteria and mechanics', 'selection process', 'praise guidelines', 'award-giving organization'],
  kra4_academic_experience: ['academic service', 'higher education', 'service record', 'certificate of employment', 'notice of appointment', 'job description', 'dean', 'faculty member'],
  kra4_industry_experience: ['industry experience', 'managerial', 'supervisory', 'technical', 'skilled', 'support staff', 'service record', 'certificate of employment', 'notice of appointment', 'job description'],
};
