import type { UploadPanelDefinition, UploadPanelKey } from './types';

export const uploadPanels: UploadPanelDefinition[] = [
  {
    key: 'kra1_teaching_effectiveness',
    kraTitle: 'KRA 1: Instruction',
    title: 'Teaching Effectiveness',
    description: 'Upload Student Evaluation of Teachers (SET) and Supervisor\'s Evaluation of Faculty (SEF) ratings, or the FEDAF for 2nd Semester AY 2025-2026. Include leave or appointment proof if applying under special status.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_curriculum_instructional_materials',
    kraTitle: 'KRA 1: Instruction',
    title: 'Instructional Materials Development',
    description: 'Upload a textbook, module, instructional manual, or multimedia teaching material you authored, or a new/revised academic program you developed, each with proof of evaluation and approval for use.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_thesis_dissertation_mentorship',
    kraTitle: 'KRA 1: Instruction',
    title: 'Research Advising and Mentorship Services',
    description: 'Upload evidence of service as a thesis, dissertation, capstone, or special project adviser or panel member, or as a student mentor/coach.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 10,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_research_outputs',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Research Outputs Published',
    description: 'Upload a published academic book, book chapter, journal article, or monograph; research translated into a project, policy, or product; or a cited research publication.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_inventions',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Inventions',
    description: 'Upload patent, utility model, or industrial design certificates, copyrighted software, a commercialized patented product, or a new plant variety, animal breed, or microbial strain.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_creative_works',
    kraTitle: 'KRA 2: Research, Innovation and/or Creative Work',
    title: 'Creative Works',
    description: 'Upload evidence for performing arts (music, dance, theatre), visual arts exhibitions, architectural/interior designs, films, or literary publications (novel, short story, poetry, essay).',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_institution',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to the Institution',
    description: 'Upload evidence for linkages, networking, or partnership activities, and institution-level income generation.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_community',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to the Community',
    description: 'Upload evidence for accreditation/QA work, judging or consultancy engagements, media appearances, resource-person/training roles, or extension project activities as lead or participant.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 50,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_extension_involvement',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Relevance and Quality of Extension Services',
    description: 'Upload the client satisfaction rating summary or the Extension Project CSS Report for your extension/outreach project(s).',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_administrative_designation',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Administrative Designation',
    description: 'Upload appointment/designation and accomplishment report evidence for an institutional or department-level administrative role.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ADMIN_DESIGNATION_ONLY',
    audienceLabel: 'Bonus - only for faculty holding an administrative designation',
  },
  {
    key: 'kra4_professional_organizations',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Involvement in Professional Organizations',
    description: 'Upload membership and active-role evidence in recognized professional organizations.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_continuing_development',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Continuing Development',
    description: 'Upload educational qualifications, conference participation, and paper presentation evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_awards_recognition',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Awards and Recognition',
    description: 'Upload awards, distinctions, and recognition evidence relevant to the faculty role.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_academic_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Academic Experience',
    description: 'Upload higher-education academic service experience documents for new entrants only.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
  {
    key: 'kra4_industry_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Industry Experience',
    description: 'Upload relevant non-academic industry experience documents for new entrants only.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
];

export const uploadPanelLabelMap: Record<UploadPanelKey, string> = uploadPanels.reduce(
  (labels, panel) => {
    labels[panel.key] = panel.title;
    return labels;
  },
  {} as Record<UploadPanelKey, string>,
);

export const uploadPanelKeywordMap: Record<UploadPanelKey, string[]> = {
  kra1_teaching_effectiveness: ['teaching effectiveness', 'student evaluation', 'supervisor evaluation', 'instruction'],
  kra1_curriculum_instructional_materials: ['curriculum', 'instructional material', 'module', 'manual', 'textbook', 'multimedia teaching material', 'academic program'],
  kra1_thesis_dissertation_mentorship: ['thesis', 'dissertation', 'mentorship', 'mentor', 'capstone', 'special project', 'panel', 'research advising'],
  kra2_research_outputs: ['research output', 'research innovation', 'journal article', 'book chapter', 'academic book', 'monograph', 'citation', 'publication'],
  kra2_inventions: ['invention', 'patent', 'utility model', 'industrial design', 'software', 'commercialized', 'plant variety', 'animal breed', 'microbial strain'],
  kra2_creative_works: ['creative work', 'performing art', 'exhibition', 'design', 'literary', 'poetry', 'novel', 'film'],
  kra3_service_to_institution: ['institution', 'partnership', 'linkage', 'networking', 'income generation'],
  kra3_service_to_community: ['community', 'consultant', 'resource person', 'outreach', 'extension project', 'media', 'accreditation', 'judge', 'examiner'],
  kra3_extension_involvement: ['client satisfaction', 'quality of extension', 'extension service', 'outreach evaluation', 'css report'],
  kra3_administrative_designation: ['administrative designation', 'appointment', 'accomplishment report', 'department head', 'dean', 'committee chair'],
  kra4_professional_organizations: ['professional organization', 'scientific society', 'membership'],
  kra4_continuing_development: ['continuing development', 'conference', 'seminar', 'workshop', 'degree', 'diploma'],
  kra4_awards_recognition: ['award', 'recognition', 'distinction'],
  kra4_academic_experience: ['academic service', 'higher education', 'dean', 'faculty member'],
  kra4_industry_experience: ['industry experience', 'managerial', 'technical', 'support staff'],
};
