import type { UploadPanelDefinition, UploadPanelKey } from './types';

export const uploadPanels: UploadPanelDefinition[] = [
  {
    key: 'kra1_teaching_effectiveness',
    kraTitle: 'KRA 1: Instruction',
    title: 'Teaching Effectiveness',
    description: 'Upload student and supervisor evaluation evidence for teaching effectiveness.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_curriculum_instructional_materials',
    kraTitle: 'KRA 1: Instruction',
    title: 'Curriculum and Instructional Materials Development',
    description: 'Upload approved curriculum revisions, instructional materials, modules, and testing materials.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra1_thesis_dissertation_mentorship',
    kraTitle: 'KRA 1: Instruction',
    title: 'Thesis, Dissertation, and Mentorship Services',
    description: 'Upload adviser, panel, capstone, special project, and mentorship evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 10,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_research_outputs',
    kraTitle: 'KRA 2: Research, Innovation and Creative Work',
    title: 'Research Outputs',
    description: 'Upload published research outputs, citations, and research translated into policy, product, or project.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_inventions',
    kraTitle: 'KRA 2: Research, Innovation and Creative Work',
    title: 'Inventions',
    description: 'Upload patent, utility model, industrial design, software, or commercialization evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra2_creative_works',
    kraTitle: 'KRA 2: Research, Innovation and Creative Work',
    title: 'Creative Works',
    description: 'Upload creative performing arts, exhibitions, designs, and literary publication evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 100,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_institution',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to Institution',
    description: 'Upload evidence for linkages, networking, partnerships, and institution-level income generation.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 30,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_service_to_community',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Service to the Community',
    description: 'Upload community service, consultancy, media, training, and outreach evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 50,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra3_extension_involvement',
    kraTitle: 'KRA 3: Extension Services',
    title: 'Extension Involvement',
    description: 'Upload client satisfaction and quality-of-extension evidence for outreach and extension services.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
  },
  {
    key: 'kra4_professional_organizations',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Involvement in Professional Organizations',
    description: 'Upload membership and active-role evidence in recognized professional organizations.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_continuing_development',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Continuing Development',
    description: 'Upload educational qualifications, conference participation, and paper presentation evidence.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 60,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_awards_recognition',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Awards and Recognitions',
    description: 'Upload awards, distinctions, and recognition evidence relevant to the faculty role.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'ALL_FACULTY',
    audienceLabel: 'For all faculty',
  },
  {
    key: 'kra4_academic_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Academic Experience',
    description: 'Upload higher-education academic service experience documents for new entrants only.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
  {
    key: 'kra4_industry_experience',
    kraTitle: 'KRA 4: Professional Development',
    title: 'Industry Experience',
    description: 'Upload relevant non-academic industry experience documents for new entrants only.',
    acceptedFormats: ['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff'],
    maxScore: 20,
    appliesTo: 'NEW_ENTRANTS_ONLY',
    audienceLabel: 'For new entrants only',
    sharedCapKey: 'kra4_new_entrant_bonus',
    sharedCapLabel: 'Combined maximum for new entrant bonus indicators',
    sharedCapMaxScore: 20,
  },
];

export const uploadPanelLabelMap: Record<UploadPanelKey, string> = uploadPanels.reduce(
  (labels, panel) => {
    labels[panel.key] = panel.title;
    return labels;
  },
  {} as Record<UploadPanelKey, string>,
);

export const uploadPanelKeywordMap: Record<UploadPanelKey, string[]> = {
  kra1_teaching_effectiveness: ['teaching effectiveness', 'student evaluation', 'supervisor evaluation', 'instruction'],
  kra1_curriculum_instructional_materials: ['curriculum', 'instructional material', 'module', 'manual', 'textbook', 'testing material'],
  kra1_thesis_dissertation_mentorship: ['thesis', 'dissertation', 'mentorship', 'mentor', 'capstone', 'special project', 'panel'],
  kra2_research_outputs: ['research output', 'research innovation', 'journal article', 'book chapter', 'monograph', 'citation', 'publication'],
  kra2_inventions: ['invention', 'patent', 'utility model', 'industrial design', 'software', 'commercialized'],
  kra2_creative_works: ['creative work', 'performing art', 'exhibition', 'design', 'literary', 'poetry', 'novel'],
  kra3_service_to_institution: ['institution', 'partnership', 'linkage', 'networking', 'income generation'],
  kra3_service_to_community: ['community', 'consultant', 'resource person', 'outreach', 'extension', 'media'],
  kra3_extension_involvement: ['client satisfaction', 'quality of extension', 'extension service', 'outreach evaluation'],
  kra4_professional_organizations: ['professional organization', 'scientific society', 'membership'],
  kra4_continuing_development: ['continuing development', 'conference', 'seminar', 'workshop', 'degree', 'diploma'],
  kra4_awards_recognition: ['award', 'recognition', 'distinction'],
  kra4_academic_experience: ['academic service', 'higher education', 'dean', 'faculty member'],
  kra4_industry_experience: ['industry experience', 'managerial', 'technical', 'support staff'],
};
